
server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: tools-mui
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 20
        max-wait: 6000
    timeout: 10000
    database: 2
  data: 
    mongodb:
      uri: mongodb://localhost:27017
      database: toolsMG
      authentication-database: admin

#阿里云
aliyun:
  #短信平台
  sms:
    accessKeyId: cc
    accessKeySecret: cc
    signName: cc
    templateCode: cc
    templateWarning: cc

---
spring:
  profiles: dev
  datasource:
    hikari:
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toolssql?useUnicode=true
    username: root
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      

server:
  port: 8080
grpc:
  client:
    remote-server:
      address: 'static://192.168.0.196:9883'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 9771